# Please do not delete this file, for the Gitpod users!
image:
    file: .gitpod.Dockerfile

tasks:
    init: |
      pnpm install
      pnpm run dev
    command: |
      .gitpod/gitpod-setup.sh

vscode:
  extensions:
    - astro-build.astro-vscode
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint

ports:
  - port: 4321
    onOpen: open-browser
